name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build-binaries:
        name: Build executables (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      ext: exe
                    - os: macos-latest
                      ext: macos
                    - os: ubuntu-latest
                      ext: linux
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Build executable with PyInstaller Action
              uses: CodeByAidan/pyinstaller-action@v1.3
              with:
                  python_ver: "3.13"
                  spec: "main.py"
                  requirements: "requirements.txt"
                  upload_exe_with_name: "Spoti2Tidal-${{ matrix.ext }}"
                  options: --onefile, --name "Spoti2Tidal", --collect-data PyQt6, --collect-submodules PyQt6, --hidden-import spotipy, --hidden-import tidalapi

    build-sdist-wheel:
        name: Build sdist/wheel
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
                  cache: "pip"
            - name: Build
              run: |
                  python -m pip install --upgrade pip build
                  python -m build
            - name: Upload dist artifacts
              uses: actions/upload-artifact@v5
              with:
                  name: dist
                  path: dist/*

    release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        needs: [build-binaries, build-sdist-wheel]
        permissions:
            contents: write
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v6
              with:
                  path: ./artifacts

            - name: List artifacts
              run: |
                  ls -R ./artifacts

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      artifacts/**
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
